name: Python BDD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BDD Tests
        run: |
          pytest --alluredir=allure-results

      - name: Inspect Allure Results
        run: |
          if [ -d "allure-results" ]; then
            echo "Allure results exist. ✅"
            ls -l allure-results
          else
            echo "❌ Allure results directory not found"
            exit 1
          fi

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

